### ISSUE TITLE
Cannot ping fs17 server

### ISSUE THREAD

**Issue by TheCipher01** [BillCipher1/Farming-Simulator2017#1]
As my issue on youtrack said I cannot connect to the server. Why did I need to add it here as well?

**Comment by BillCipher1** [comment]
I have it added to github so I know to take a closer look at it and upload any mods that might be fixed as a cause of this.

**Comment by TheCipher01** [comment]
@BillCipher1 Okay so what about the one on YouTrack?

**Comment by BillCipher1** [comment]
@CreepersplaysMC It will remain on youtrack as in progress.

**Comment by TheCipher01** [comment]
Okay, what do you think the issue is?

**Comment by BillCipher1** [comment]
Please add the following mod to your game and see if you can connect then. #3

**Comment by TheCipher01** [comment]
That worked.

**Comment by BillCipher1** [comment]
Alright forgot to add that we added that to prevent some lag. Thanks. Will close the issue on youtrack as well.

**Comment by CreepersplaysMC** [comment]
ok
